### PR TITLE
ran update.sh to update to v3.0.0

### PR DESCRIPTION
**Pull request by juliencarnot**
piwik 3.0.0 is out!

### CODE REVIEW

**Comment by tianon** [comment]
Nice! :+1:

**Comment by tianon** [comment]
@pierreozoux looks like @docker-library-bot could use some commit bits here to automate this one too :smile:

**Comment by pierreozoux** [comment]
@tianon it was referenced here: https://github.com/docker-library/official-images/issues/1321

did you do it, or should I open a new issue?

Thanks :)

**Comment by tianon** [comment]
@pierreozoux I used to do the updates by hand, so I have piwik in my local list, but we've since started using Jenkins instead for the majority of repos (making my by-hand update checks less frequent), so if you give @docker-library-bot commit access to this repo, I can make it properly automated :+1:

**Comment by pierreozoux** [comment]
@tianon done :)

**Comment by tianon** [comment]
https://doi-janky.infosiftr.net/job/update.sh/job/piwik/ :metal:

**Pull request merged**
